# <<< conda initialize <<<
conda activate ahc-ete
# conda activate test mask-rcnn  test



export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

export PATH=~/matlab/bin${PATH:+:${PATH}}

# for my project
#export PYTHONPATH=$HOME/tuat${PYTHONPATH:+:${PYTHONPATH}}
# export PYTHONPATH=$HOME/FastRefining${PYTHONPATH:+:${PYTHONPATH}}


